version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"



  web:
    build: .
    command: npm start
    volumes:
       - .:/usr/app/
    ports:
      - "3000:3000"
    depends_on:
      - db

  pgadmin:
      image: fenglc/pgadmin4

      ports:
        - "5050:5050"

      depends_on:
        - web
